### ISSUE TITLE
【布局】页脚置底

### ISSUE THREAD

**Issue by Soffiaa** [Soffiaa/learning_notes#3]
页脚置底，英文叫stick footer，就是使得页脚无论如何都固定在页面底部。
看似简单的一种布局，可不是<code>position:fixed</code>就能搞定的呢。
>  假设我们要做一个带页脚的页面，页面初始状态内容很少，是没有滚动条的；当页面触发某个功能，页面内容会变多，以致页面会出现滚动条。
### 方法1：对页脚以外的部分进行<code>min-height: calc(100vh - 页脚高度)</code>设置
```
<style>
body{
   height:100%;
   overflow:auto;
}
.main{
  width:100%;
  min-height:calc(100vh - 300px);
}
.footer{
  width:100%;
  height:100px;
  margin-top:200px;
}
</style>
<body>
<div class="main"></div>
<div class="footer"></div>
</body>
```
### 方法2：flex之justify-content:space-between
```html
<body>
	<div class="main"></div>
	<div class="footer">footer</div>
</body>
```

```css
 html, body {
   width: 100%;
   height: 100%;
   padding: 0;
   margin: 0;
 }
 body {
   display: flex;
   flex-direction: column;
   justify-content: space-between;
   overflow: auto;
 }
 .main {
   width: 100%;
   height: 100px;
   flex-shrink: 0;
 }
 .footer {
   width: 100%;
   height: 100px;
   text-align: center;
   margin-top: 200px;
 }
```

```javascript
let addHeight = false;
const mainDom = document.getElementsByClassName('main')[ 0 ];
mainDom.onclick = function() {
    if (!addHeight) {
        mainDom.style.height = '1000px';
    } else {
        mainDom.style.height = '100px';
    }
    addHeight = !addHeight;
};
```
